export const ALL_STUDENTS_REQUEST = `STUDENTS/ALL_STUDENTS_REQUEST`;
export const ALL_STUDENTS_SUCCESS = `STUDENTS/ALL_STUDENTS_SUCCESS`;
export const ALL_STUDENTS_ERROR = `STUDENTS/ALL_STUDENTS_ERROR`;

export const STUDENT_CREATE_REQUEST = `STUDENTS/STUDENT_CREATE_REQUEST`;
export const STUDENT_CREATE_SUCCESS = `STUDENTS/STUDENT_CREATE_SUCCESS`;
export const STUDENT_CREATE_ERROR = `STUDENTS/STUDENT_CREATE_ERROR`;

export const STUDENT_UPDATE_REQUEST = `STUDENTS/STUDENT_UPDATE_REQUEST`;
export const STUDENT_UPDATE_SUCCESS = `STUDENTS/STUDENT_UPDATE_SUCCESS`;
export const STUDENT_UPDATE_ERROR = `STUDENTS/STUDENT_UPDATE_ERROR`;

export const STUDENT_DELETE_REQUEST = `STUDENTS/STUDENT_DELETE_REQUEST`;
export const STUDENT_DELETE_SUCCESS = `STUDENTS/STUDENT_DELETE_SUCCESS`;
export const STUDENT_DELETE_ERROR = `STUDENTS/STUDENT_DELETE_ERROR`;