export const ALL_STUDENTS_REQUEST = `STUDENTS/ALL_STUDENTS_REQUEST`;
export const ALL_STUDENTS_SUCCESS = `STUDENTS/ALL_STUDENTS_SUCCESS`;
export const ALL_STUDENTS_ERROR = `STUDENTS/ALL_STUDENTS_ERROR`;