export const LOGIN_REQUEST = `STUDENTS/LOGIN_REQUEST`;
export const LOGIN_SUCCESS = `STUDENTS/LOGIN_SUCCESS`;
export const LOGIN_ERROR = `STUDENTS/LOGIN_ERROR`;

export const SIGN_UP_REQUEST = `STUDENTS/SIGN_UP_REQUEST`;
export const SIGN_UP_SUCCESS = `STUDENTS/SIGN_UP_SUCCESS`;
export const SIGN_UP_ERROR = `STUDENTS/SIGN_UP_ERROR`;
